version: "3.3"
services:
  frontend:
    build: ./client
    ports:
      - 3000:3000
  backend:
    build: ./server
    ports:
      - 8000:8000
    links:
      - db
  db:
    image: mongo
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
volumes:
  node_modules:
